### ISSUE TITLE
Update Person Function Overrides Existing Avatars

### ISSUE THREAD

**Issue by MikeRalston98** [kctrey/wxcadm#8]
When the "update_person" within person.py, the user's avatar is not one of the fields automatically populated. As such, when running the "PUT" to v1/people/{personId} they are set back to the default avatar of their initials. 

This can be recreated by calling any method that then references the update_person function to send the changes.

**Comment by kctrey** [comment]
This is a known issue with the APIs because of the divergence of the SCIM API from the People API. I believe a fix is coming, but until recently, Avatar only existed in the SCIM API, but that API doesn't have the ability to update Webex Calling settings. There has been an update to the People API, but I don't believe it is working. Once it does, I will get it into the next __wxcadm__ version.

**Comment by kctrey** [comment]
Turns out this has been resolved on the Webex side, and I have added new Person attributes to handle it. Fixed in 4.2.6.
